### ISSUE TITLE
Probably improper usage of T-Regx?

### ISSUE THREAD

**Issue by danon** [JoseVale99/DatosApp#1]
Hey, @JoseVale99 , cool app you got here!

I noticed your file, here: [DataController.php](https://github.com/JoseVale99/DatosApp/blob/1f3eb70e86530949b6a43a241b6783e6ec2676d4/app/Http/Controllers/DataController.php), and I also noticed you imported `use TRegx\SafeRegex\preg;`, so I guess you wanted to use safe regular expressions?

But there may be an error, because this is still using vanilla `preg_match()` (which has all the errors):
```php
case preg_match("/^([-0-9]+[.]([0-9]+))?$/", $request->dato):
    return back()->with('message', "float $request->dato");
    break;
case preg_match("/^([a-z A-Z @ # ~ € & · $ ( )  % = ? { } - + * |])$/", $request->dato):
    return back()->with('message', "char $request->dato");
    break;
```

To be protected from errors you need to either use `SafeRegex` (notice `preg::`)
```php
preg::match("/^([-0-9]+[.]([0-9]+))?$/", $request->dato):
```
Or `CleanRegex`
```php
pattern('^([-0-9]+[.]([0-9]+))?$')->test($request->dato);
```

**Comment by JoseVale99** [comment]
excellent, thanks friend.
